apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: dockerdotnetlearning.api:latest
          imagePullPolicy: Never # Para poder hacer pull localhost ?
          ports:
            - containerPort: 80
